FROM ubuntu:16.04 
RUN apt-get update
RUN apt-get install -y libssl-dev build-essential
RUN mkdir /app 
ADD build/imagestore /app
COPY librdkafka.tar.gz /app/
WORKDIR /app/
RUN chmod 755 librdkafka.tar.gz
RUN tar -xvf librdkafka.tar.gz
WORKDIR /app/librdkafka/
RUN ./configure 
#--prefix=/usr/local/lib/
RUN make
RUN make install
WORKDIR /app
RUN rm -r /app/librdkafka
RUN rm librdkafka.tar.gz
RUN export LD_LIBRARY_PATH=/usr/local/lib/
RUN ldconfig
CMD ["./imagestore"]
