---
apiVersion: v1
kind: Service
metadata:
  name: imagestore
  namespace: "{{ .Values.namespace }}" 
  labels:
    app: imagestore
spec:
  type: "{{ .Values.service.type }}" 
  selector:
    app: imagestore
  ports:
  - name: imagestore
    port: 8081 
    targetPort: 8081
    protocol: TCP
