---
apiVersion: v1
kind: Service
metadata:
  name: kafka-np
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - nodePort: 30000
    port: 30000
    protocol: TCP
    targetPort: 9092
  selector:
   app: kafka
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }} 
spec:
  clusterIP: None
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
