apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }} 
spec:
  replicas: {{ .Values.service.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      annotations:
        cni: calico
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: BROKER_ID_COMMAND
          value: "hostname | awk -F '-' '{print $2}'"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_PORT
          value: "30000"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: {{ .Values.service.kafka.advertisedHostName }}
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_HEAP_OPTS
          value: -Xmx256M -Xms128M
        image: {{ .Values.service.kafka.image }}
        name: kafka
        ports:
        - containerPort: 9092
{{- if .Values.persistentVolume.enabled }}
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      storageClassName: manual
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
{{- end }}
