#
BUILD_PATH=../build
####################################################################################
# Specify the name of the binary here
BIN=$(BUILD_PATH)/imagestore

####################################################################################

# This should be the last line
include ../makefile.defs
