apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }} 
spec:
  replicas: {{ .Values.service.zookeeper.replicas }}
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zoo
  template:
    metadata:
      annotations:
        cni: calico
      labels:
        app: zookeeper
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ZOO_MY_ID
          value: '1'
        image: {{ .Values.service.zookeeper.image }}
        name: zoo
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
{{- if .Values.persistentVolume.enabled }}
        volumeMounts:
        - name: zoo
          mountPath: /opt/zookeeper-3.4.13/data 
  volumeClaimTemplates:
  - metadata:
      name: zoo
    spec:
      storageClassName: manual
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
{{- end }}
