{{- if .Values.persistentVolume.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zoo-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/zookeeper"
{{- end }}
